CREATE TABLE "WEBAPPSDB".MSTR_USERS
(  user_id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY, 
   username VARCHAR(200) NOT NULL,
 password VARCHAR(200) NOT NULL, 
email VARCHAR(300) NOT NULL,
 f_name VARCHAR(100) NOT NULL,
 l_name VARCHAR(100) NOT NULL,
 address LONG VARCHAR , 
city VARCHAR(100) NOT NULL,
 country VARCHAR(100) NOT NULL,
 phone BIGINT , 
isdcode INT , 
mobile BIGINT , 
rest_id BIGINT ,
 join_date DATE NOT NULL,
 join_time TIMESTAMP NOT NULL,
 acc_type VARCHAR(10) NOT NULL, 
log_id BIGINT NOT NULL)


ALTER TABLE MSTR_USERS DROP COLUMN LOG_ID